-- 코드를 입력하세요
SELECT
       c.AUTHOR_ID
     , c.AUTHOR_NAME
     , b.CATEGORY
     , sum(a.SALES * b.PRICE) as TOTAL_SALES
  FROM BOOK_SALES a
  JOIN BOOK b on a.BOOK_ID = b.BOOK_ID
  JOIN AUTHOR c on b.AUTHOR_ID = c.AUTHOR_ID
 WHERE a.SALES_DATE LIKE '2022-01-%'
 GROUP BY c.AUTHOR_ID, b.CATEGORY
 ORDER BY c.AUTHOR_ID, b.CATEGORY DESC;
  